[mgr]
cwd = { fg = "#179299" }

hovered         = { fg = "#eff1f5", bg = "#d20f39" }
preview_hovered = { fg = "#eff1f5", bg = "#4c4f69" }

find_keyword  = { fg = "#df8e1d", italic = true }
find_position = { fg = "#ea76cb", bg = "reset", italic = true }

marker_copied   = { fg = "#40a02b", bg = "#40a02b" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }
marker_marked   = { fg = "#179299", bg = "#179299" }
marker_selected = { fg = "#d20f39", bg = "#d20f39" }

count_copied   = { fg = "#eff1f5", bg = "#40a02b" }
count_cut      = { fg = "#eff1f5", bg = "#d20f39" }
count_selected = { fg = "#eff1f5", bg = "#d20f39" }

border_symbol = "│"
border_style  = { fg = "#8c8fa1" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[tabs]
active   = { fg = "#eff1f5", bg = "#4c4f69", bold = true }
inactive = { fg = "#4c4f69", bg = "#bcc0cc" }

[mode]
normal_main = { fg = "#eff1f5", bg = "#d20f39", bold = true }
normal_alt  = { fg = "#d20f39", bg = "#ccd0da"}

select_main = { fg = "#eff1f5", bg = "#40a02b", bold = true }
select_alt  = { fg = "#40a02b", bg = "#ccd0da"}

unset_main  = { fg = "#eff1f5", bg = "#dd7878", bold = true }
unset_alt   = { fg = "#dd7878", bg = "#ccd0da"}

[status]
separator_open  = ""
separator_close = ""

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#bcc0cc" }
progress_error  = { fg = "#d20f39", bg = "#bcc0cc" }

perm_type  = { fg = "#1e66f5" }
perm_read  = { fg = "#df8e1d" }
perm_write = { fg = "#d20f39" }
perm_exec  = { fg = "#40a02b" }
perm_sep   = { fg = "#8c8fa1" }

[input]
border   = { fg = "#d20f39" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#d20f39" }
active   = { fg = "#ea76cb" }
inactive = {}

[confirm]
border     = { fg = "#d20f39" }
title      = { fg = "#d20f39" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#d20f39" }

[tasks]
border  = { fg = "#d20f39" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#ccd0da" }
cand            = { fg = "#179299" }
rest            = { fg = "#7c7f93" }
desc            = { fg = "#ea76cb" }
separator       = "  "
separator_style = { fg = "#acb0be" }

[help]
on      = { fg = "#179299" }
run     = { fg = "#ea76cb" }
desc    = { fg = "#7c7f93" }
hovered = { bg = "#acb0be", bold = true }
footer  = { fg = "#4c4f69", bg = "#bcc0cc" }

[notify]
title_info  = { fg = "#179299" }
title_warn  = { fg = "#df8e1d" }
title_error = { fg = "#d20f39" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#179299" },
	{ mime = "{audio,video}/*", fg = "#df8e1d" },

	# Archives
	{ mime = "application/*zip", fg = "#ea76cb" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ea76cb" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#40a02b" },

	# Fallback
	{ name = "*", fg = "#4c4f69" },
	{ name = "*/", fg = "#d20f39" }
]

[spot]
border = { fg = "#d20f39" }
title  = { fg = "#d20f39" }
tbl_cell = { fg = "#d20f39", reversed = true }
tbl_col = { bold = true }
