[mgr]
cwd = { fg = "#81c8be" }

hovered         = { fg = "#303446", bg = "#e5c890" }
preview_hovered = { fg = "#303446", bg = "#c6d0f5" }

find_keyword  = { fg = "#e5c890", italic = true }
find_position = { fg = "#f4b8e4", bg = "reset", italic = true }

marker_copied   = { fg = "#a6d189", bg = "#a6d189" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }
marker_marked   = { fg = "#81c8be", bg = "#81c8be" }
marker_selected = { fg = "#e5c890", bg = "#e5c890" }

count_copied   = { fg = "#303446", bg = "#a6d189" }
count_cut      = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#e5c890" }

border_symbol = "│"
border_style  = { fg = "#838ba7" }

syntect_theme = "~/.config/yazi/Catppuccin-frappe.tmTheme"

[tabs]
active   = { fg = "#303446", bg = "#c6d0f5", bold = true }
inactive = { fg = "#c6d0f5", bg = "#51576d" }

[mode]
normal_main = { fg = "#303446", bg = "#e5c890", bold = true }
normal_alt  = { fg = "#e5c890", bg = "#414559"}

select_main = { fg = "#303446", bg = "#a6d189", bold = true }
select_alt  = { fg = "#a6d189", bg = "#414559"}

unset_main  = { fg = "#303446", bg = "#eebebe", bold = true }
unset_alt   = { fg = "#eebebe", bg = "#414559"}

[status]
separator_open  = ""
separator_close = ""

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8caaee", bg = "#51576d" }
progress_error  = { fg = "#e78284", bg = "#51576d" }

perm_type  = { fg = "#8caaee" }
perm_read  = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec  = { fg = "#a6d189" }
perm_sep   = { fg = "#838ba7" }

[input]
border   = { fg = "#e5c890" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#e5c890" }
active   = { fg = "#f4b8e4" }
inactive = {}

[confirm]
border     = { fg = "#e5c890" }
title      = { fg = "#e5c890" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#e5c890" }

[tasks]
border  = { fg = "#e5c890" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#414559" }
cand            = { fg = "#81c8be" }
rest            = { fg = "#949cbb" }
desc            = { fg = "#f4b8e4" }
separator       = "  "
separator_style = { fg = "#626880" }

[help]
on      = { fg = "#81c8be" }
run     = { fg = "#f4b8e4" }
desc    = { fg = "#949cbb" }
hovered = { bg = "#626880", bold = true }
footer  = { fg = "#c6d0f5", bg = "#51576d" }

[notify]
title_info  = { fg = "#81c8be" }
title_warn  = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#81c8be" },
	{ mime = "{audio,video}/*", fg = "#e5c890" },

	# Archives
	{ mime = "application/*zip", fg = "#f4b8e4" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f4b8e4" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6d189" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#e5c890" }
]

[spot]
border = { fg = "#e5c890" }
title  = { fg = "#e5c890" }
tbl_cell = { fg = "#e5c890", reversed = true }
tbl_col = { bold = true }
