[mgr]
cwd = { fg = "#8bd5ca" }

hovered         = { fg = "#24273a", bg = "#f5bde6" }
preview_hovered = { fg = "#24273a", bg = "#cad3f5" }

find_keyword  = { fg = "#eed49f", italic = true }
find_position = { fg = "#f5bde6", bg = "reset", italic = true }

marker_copied   = { fg = "#a6da95", bg = "#a6da95" }
marker_cut      = { fg = "#ed8796", bg = "#ed8796" }
marker_marked   = { fg = "#8bd5ca", bg = "#8bd5ca" }
marker_selected = { fg = "#f5bde6", bg = "#f5bde6" }

count_copied   = { fg = "#24273a", bg = "#a6da95" }
count_cut      = { fg = "#24273a", bg = "#ed8796" }
count_selected = { fg = "#24273a", bg = "#f5bde6" }

border_symbol = "│"
border_style  = { fg = "#8087a2" }

syntect_theme = "~/.config/yazi/Catppuccin-macchiato.tmTheme"

[tabs]
active   = { fg = "#24273a", bg = "#cad3f5", bold = true }
inactive = { fg = "#cad3f5", bg = "#494d64" }

[mode]
normal_main = { fg = "#24273a", bg = "#f5bde6", bold = true }
normal_alt  = { fg = "#f5bde6", bg = "#363a4f"}

select_main = { fg = "#24273a", bg = "#a6da95", bold = true }
select_alt  = { fg = "#a6da95", bg = "#363a4f"}

unset_main  = { fg = "#24273a", bg = "#f0c6c6", bold = true }
unset_alt   = { fg = "#f0c6c6", bg = "#363a4f"}

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8aadf4", bg = "#494d64" }
progress_error  = { fg = "#ed8796", bg = "#494d64" }

perm_type  = { fg = "#8aadf4" }
perm_read  = { fg = "#eed49f" }
perm_write = { fg = "#ed8796" }
perm_exec  = { fg = "#a6da95" }
perm_sep   = { fg = "#8087a2" }

[input]
border   = { fg = "#f5bde6" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#f5bde6" }
active   = { fg = "#f5bde6" }
inactive = {}

[confirm]
border     = { fg = "#f5bde6" }
title      = { fg = "#f5bde6" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#f5bde6" }

[tasks]
border  = { fg = "#f5bde6" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#363a4f" }
cand            = { fg = "#8bd5ca" }
rest            = { fg = "#939ab7" }
desc            = { fg = "#f5bde6" }
separator       = "  "
separator_style = { fg = "#5b6078" }

[help]
on      = { fg = "#8bd5ca" }
run     = { fg = "#f5bde6" }
desc    = { fg = "#939ab7" }
hovered = { bg = "#5b6078", bold = true }
footer  = { fg = "#cad3f5", bg = "#494d64" }

[notify]
title_info  = { fg = "#8bd5ca" }
title_warn  = { fg = "#eed49f" }
title_error = { fg = "#ed8796" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#8bd5ca" },
	{ mime = "{audio,video}/*", fg = "#eed49f" },

	# Archives
	{ mime = "application/*zip", fg = "#f5bde6" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5bde6" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6da95" },

	# Fallback
	{ name = "*", fg = "#cad3f5" },
	{ name = "*/", fg = "#f5bde6" }
]

[spot]
border = { fg = "#f5bde6" }
title  = { fg = "#f5bde6" }
tbl_cell = { fg = "#f5bde6", reversed = true }
tbl_col = { bold = true }
